config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  post 'home/set_colour', as: :set_colour
  post 'home/off', as: :off

   root 'home#index'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end


  def set_colour
  	
 	@colour=params[:rgb][:colour]

	m = @colour.match /#(..)(..)(..)/

	@r = "#{m[1].hex}"
	@g = "#{m[2].hex}"
	@b = "#{m[3].hex}"

	green(@g.to_f/255)
	blue(@b.to_f/255)
	red(@r.to_f/255)


  end


def off
    green(0)
  blue(0)
  red(0)

end


private

def green(value)
  system "echo \"17=#{value.to_f}\" > /dev/pi-blaster" 	
end

def blue(value)
  system "echo \"18=#{value.to_f}\" > /dev/pi-blaster"
end

def red(value)
  system "echo \"23=#{value.to_f}\" > /dev/pi-blaster"
end




end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<%= link_to "White", set_colour_path("rgb[colour]"=> "#ffffff"), remote: true, method: :post %>

<%= link_to "Off", set_colour_path("rgb[colour]"=> "#000000"), remote: true, method: :post %>

<%= link_to "Green", set_colour_path("rgb[colour]"=> "#00ff00"), remote: true, method: :post %>
<%= link_to "Red", set_colour_path("rgb[colour]"=> "#ff0000"), remote: true, method: :post %>
<%= link_to "Blue", set_colour_path("rgb[colour]"=> "#0000ff"), remote: true, method: :post %>


<%= form_tag set_colour_path, remote: true do %>

	<%=color_field :rgb, :colour %>
	<%=submit_tag %>


<% end %>



<%= form_tag off_path, remote: true do %>

	
	<%=submit_tag "Turn Off" %>


<% end %>


<div class="colour-set">
	
</div>

app/views/home/off.js.erb
$(".colour-set").html("Off");
$(".colour-set").css("background-color", "white");


//alert("r:<%=@r%> g:<%=@g%> b:<%=@b%> and % r:<%=@r.to_f/255%> g:<%=@g.to_f/255%> b:<%=@b.to_f/255%>")

app/views/home/set_colour.html.erb
R:<%=@r%><br>
G:<%=@g%><br>
B:<%=@b%><br>

app/views/home/set_colour.js.erb
$(".colour-set").html("Red:<%=@r%> Green:<%=@g%> Blue:<%=@b%> (<%=@colour%>)");
$(".colour-set").css("background-color", "<%=@colour%>");


//alert("r:<%=@r%> g:<%=@g%> b:<%=@b%> and % r:<%=@r.to_f/255%> g:<%=@g.to_f/255%> b:<%=@b.to_f/255%>")

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RgbLights</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>